dataDir<-'work/diff'
dataType<-'gene'
geneDiffFile<-sprintf('%s/%s_exp.diff',dataDir,dataType)
outFile<-sprintf('out/%s_exp.diff.gz',dataType)
geneDiff<-read.table(geneDiffFile,header=TRUE,stringsAsFactors=FALSE)
kgXref<-read.table('~/installs/star/kgXRef.tsv.gz',sep='\t',stringsAsFactors=FALSE,quote='',comment='',header=TRUE)
rownames(kgXref)<-kgXref$X.kgID
geneDiff$name<-kgXref[geneDiff$gene_id,'geneSymbol']
geneDiff$ncbi<-kgXref[geneDiff$gene_id,'mRNA']
kgAlias<-read.table('~/installs/star/kgAlias.tsv.gz',sep='\t',stringsAsFactors=FALSE,quote='',comment='',header=TRUE)
kgAlias<-kgAlias[kgAlias$X.kgID!=kgAlias$alias,]
aliases<-tapply(kgAlias$alias,kgAlias$X.kgID,paste,collapse='|')
geneDiff$name[is.na(geneDiff$name)]<-aliases[geneDiff$gene_id[is.na(geneDiff$name)]]
knownToEnsembl<-read.table('~/installs/star/knownToEnsembl.tsv.gz',sep='\t',stringsAsFactors=FALSE,quote='',comment='',header=TRUE)
rownames(knownToEnsembl)<-knownToEnsembl$X.name
geneDiff$ensembl<-knownToEnsembl[geneDiff$gene_id,'value']
knownToKeggEntrez<-read.table('~/installs/star/knownToKeggEntrez.tsv.gz',sep='\t',stringsAsFactors=FALSE,quote='',comment='',header=TRUE)
knownToKeggEntrez$entrez<-sub('^.*\\+','',knownToKeggEntrez$keggEntrez)
knownToKeggEntrez<-unique(knownToKeggEntrez[,c('X.name','entrez')])
rownames(knownToKeggEntrez)<-knownToKeggEntrez$X.name
#geneDiff$entrez<-knownToKeggEntrez[geneDiff$gene_id,'entrez']
write.csv(geneDiff,gzfile(outFile))

